### ISSUE TITLE
Calling `next` in `afterDestroy()` throwing error

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-faq-model-hooks#1]
#STR
1. Clone the project
2. `slc run`

[This line](https://github.com/strongloop/loopback-faq-model-hooks/blob/master/common/models/coffee-shop.js#L60) is causing the error at the end of the console output.

**Comment by superkhau** [comment]
@raymondfeng Can you reproduce this to confirm the bug?

**Comment by raymondfeng** [comment]
Fixed by https://github.com/strongloop/loopback-faq-model-hooks/commit/fd974b88cd6d5f7f88c461df87fdc9e1f7de6d6d. It's a user error in the faq app.

**Comment by superkhau** [comment]
Cool thanks.
